#include "adventure.h"
#include "world_runtime.h"
#include "npc.h"
static int event_item(int id){switch(id){case 0:return ITEM_TICKET;case 11:return ITEM_LETTER;case 12:return ITEM_BLUE_KEY;case 15:return ITEM_UMBRELLA;case 17:case 18:case 19:case 20:return ITEM_PORTRAIT;case 21:return ITEM_TEACUP;case 27:case 28:case 29:case 30:case 31:case 32:case 33:return ITEM_TINY_GEAR;case 35:return ITEM_LUNCHBOX;case 37:return ITEM_LOOSE_COG;default:return -1;}}
static void consume_chain_item(MokoAdventure*a,int id){switch(id){case 1:items_take(&a->inventory,ITEM_TICKET,1);break;case 13:items_take(&a->inventory,ITEM_BLUE_KEY,1);break;case 22:items_take(&a->inventory,ITEM_TEACUP,1);break;case 36:items_take(&a->inventory,ITEM_LUNCHBOX,1);break;default:break;}}
static int npc_delivery(int npc,int*item,int*amount){*item=-1;*amount=0;switch(npc){case 2:*item=ITEM_LETTER;*amount=1;return 29;case 3:*item=ITEM_UMBRELLA;*amount=1;return 6;case 4:*item=ITEM_PORTRAIT;*amount=4;return 32;case 6:*item=ITEM_LUNCHBOX;*amount=1;return 38;case 7:*item=ITEM_TINY_GEAR;*amount=7;return 36;default:return -1;}}
static int deliveries_clear(const MokoAdventure*a){int i,n=0;for(i=0;i<10;i++)if(adventure_npc_delivery_required(i)&&a->npc_delivered[i])n++;return n;}
static int quests_clear_except_final(const MokoAdventure*a){int i,n=0;for(i=0;i<MOKO_QUEST_COUNT;i++)if(i!=47&&quests_is_clear(&a->quests,i))n++;return n;}
static void update_true_completion(MokoAdventure*a){int deliveries=deliveries_clear(a),quests=quests_clear_except_final(a);if(deliveries>=5&&quests>=MOKO_QUEST_COUNT-1){quests_trigger(&a->quests,47);quests_clear(&a->quests,47);}}
static void challenge_notice(MokoAdventure*a,int quest){a->challenge_notice_quest=quest;a->challenge_notice_timer=120;}
void adventure_journal_sync(MokoAdventure*a){journal_sync(&a->journal,&a->quests,&a->inventory);}
void adventure_journal_move(MokoAdventure*a,int dir){if(a->journal.tab==0)journal_next_quest(&a->journal,&a->quests,dir);else journal_next_item(&a->journal,&a->inventory,dir);}
void adventure_journal_tab(MokoAdventure*a){journal_toggle_tab(&a->journal);adventure_journal_sync(a);}
void adventure_story_progress(MokoAdventure*a,int quest,int amount){quests_trigger(&a->quests,quest);quests_add(&a->quests,quest,amount);adventure_journal_sync(a);}
void adventure_story_clear(MokoAdventure*a,int quest){quests_trigger(&a->quests,quest);quests_clear(&a->quests,quest);adventure_journal_sync(a);}
void adventure_challenge_zone(MokoAdventure*a,int room,int zone,int dashing){uint8_t bit;int quest=-1;if(room<0||room>4||zone<0||zone>7)return;bit=(uint8_t)(1u<<zone);if(a->challenge_flags[room]&bit)return;if(room==1&&zone<2)quest=5;else if(room==2&&zone<3)quest=9;else if(room==3&&zone<2&&dashing)quest=13;if(quest<0)return;a->challenge_flags[room]|=bit;adventure_story_progress(a,quest,1);challenge_notice(a,quest);}
void adventure_challenge_position(MokoAdventure*a,int room,int px,int py,int dashing){if(room==1){if(px>=34&&px<=78&&py>=128&&py<=178)adventure_challenge_zone(a,1,0,dashing);if(px>=236&&px<=282&&py>=128&&py<=178)adventure_challenge_zone(a,1,1,dashing);}else if(room==2){if(px>=34&&px<=72&&py>=92&&py<=154)adventure_challenge_zone(a,2,0,dashing);if(px>=142&&px<=180&&py>=92&&py<=154)adventure_challenge_zone(a,2,1,dashing);if(px>=238&&px<=276&&py>=92&&py<=154)adventure_challenge_zone(a,2,2,dashing);}else if(room==3){if(px>=168&&px<=194&&py>=128&&py<=204)adventure_challenge_zone(a,3,0,dashing);if(px>=228&&px<=254&&py>=62&&py<=164)adventure_challenge_zone(a,3,1,dashing);}}
int adventure_npc_talk(MokoAdventure*a,int npc_index){const MokoNpcDef*n=npc_get(npc_index);int item,amount,q;if(!n||npc_index<0||npc_index>=10)return 0;if(!a->npc_met[npc_index]){a->npc_met[npc_index]=1;quests_trigger(&a->quests,n->quest);adventure_journal_sync(a);return 1;}q=npc_delivery(npc_index,&item,&amount);if(q>=0&&!a->npc_delivered[npc_index]&&items_has(&a->inventory,item,amount)){items_take(&a->inventory,item,amount);a->npc_delivered[npc_index]=1;if(!quests_is_clear(&a->quests,q))adventure_story_clear(a,q);else adventure_journal_sync(a);a->last_reward=100+amount*25;a->quests.ap+=(uint32_t)(50+amount*10);a->notice_timer=150;update_true_completion(a);return 2;}return 0;}
int adventure_npc_met(const MokoAdventure*a,int npc_index){return npc_index>=0&&npc_index<10?a->npc_met[npc_index]:0;}
int adventure_npc_delivered(const MokoAdventure*a,int npc_index){return npc_index>=0&&npc_index<10?a->npc_delivered[npc_index]:0;}
int adventure_npc_delivery_required(int npc_index){int item,amount;return npc_delivery(npc_index,&item,&amount)>=0;}
int adventure_npc_reward(const MokoAdventure*a){return a->last_reward;}
void adventure_reset(MokoAdventure*a){int i;quests_reset(&a->quests);world_events_reset(&a->world);items_reset(&a->inventory);journal_reset(&a->journal);a->last_event=-1;a->last_reward=0;a->notice_timer=0;a->dash_count=0;a->current_room=0;a->room_start_health=3;a->challenge_notice_quest=-1;a->challenge_notice_timer=0;for(i=0;i<5;i++)a->challenge_flags[i]=0;for(i=0;i<10;i++){a->npc_met[i]=0;a->npc_delivered[i]=0;}world_events_enter_room(&a->world,0,&a->quests);world_runtime_bind_adventure(a);adventure_journal_sync(a);}
void adventure_tick(MokoAdventure*a,int room,int shards,int echoes,int combo,int health,int focus){if(room!=a->current_room){if(a->current_room>=0&&a->current_room<4&&health>=3)adventure_story_clear(a,42);a->current_room=room;a->room_start_health=health;world_events_enter_room(&a->world,room,&a->quests);}quests_tick(&a->quests,room,shards,echoes,combo,health,focus);update_true_completion(a);adventure_journal_sync(a);if(a->notice_timer>0)a->notice_timer--;if(a->challenge_notice_timer>0)a->challenge_notice_timer--;}
int adventure_interact(MokoAdventure*a,int room,int px,int py){int id=world_events_near(&a->world,room,px,py,24),item,reward;if(id<0||!world_event_unlocked(&a->world,&a->quests,id))return 0;if(id==1&&!items_has(&a->inventory,ITEM_TICKET,1))return 0;if(id==13&&!items_has(&a->inventory,ITEM_BLUE_KEY,1))return 0;if(id==22&&!items_has(&a->inventory,ITEM_TEACUP,1))return 0;if(id==36&&!items_has(&a->inventory,ITEM_LUNCHBOX,1))return 0;reward=world_events_interact(&a->world,&a->quests,room,px,py,24);if(!reward)return 0;consume_chain_item(a,id);item=event_item(id);if(item>=0)items_add(&a->inventory,item,1);adventure_journal_sync(a);a->last_event=id;a->last_reward=reward>1?reward:0;a->notice_timer=150;update_true_completion(a);return reward;}
void adventure_dash(MokoAdventure*a){a->dash_count++;quests_trigger(&a->quests,40);quests_add(&a->quests,40,1);quests_trigger(&a->quests,41);quests_add(&a->quests,41,1);}
int adventure_completion(const MokoAdventure*a){int i,done=0;for(i=0;i<MOKO_QUEST_COUNT;i++)if(quests_is_clear(&a->quests,i))done++;for(i=0;i<10;i++)if(adventure_npc_delivery_required(i)&&a->npc_delivered[i])done++;return(done*100)/(MOKO_QUEST_COUNT+5);}
const char*adventure_notice(const MokoAdventure*a){const MokoWorldEventDef*d;if(a->last_event<0)return "";d=world_event_def(a->last_event);return d?d->label:"";}
const char*adventure_challenge_notice(const MokoAdventure*a){if(a->challenge_notice_quest<0)return "";return quests_name(a->challenge_notice_quest);}
int adventure_near_event(const MokoAdventure*a,int room,int px,int py,int radius){int id=world_events_near(&a->world,room,px,py,radius);if(id<0||!world_event_unlocked(&a->world,&a->quests,id))return -1;if(id==1&&!items_has(&a->inventory,ITEM_TICKET,1))return -1;if(id==13&&!items_has(&a->inventory,ITEM_BLUE_KEY,1))return -1;if(id==22&&!items_has(&a->inventory,ITEM_TEACUP,1))return -1;if(id==36&&!items_has(&a->inventory,ITEM_LUNCHBOX,1))return -1;return id;}
int adventure_room_remaining(const MokoAdventure*a,int room){return world_events_remaining(&a->world,room);}
const MokoWorldEventDef*adventure_event(const MokoAdventure*a,int index){(void)a;return world_event_def(index);}
int adventure_item_count(const MokoAdventure*a,int item){return(item>=0&&item<ITEM_COUNT)?a->inventory.count[item]:0;}
