#include "enemies.h"
typedef struct {uint8_t room,kind;short x,y;} Spawn;
static const Spawn spawns[MOKO_ENEMY_COUNT]={{0,ENEMY_TICKHOUND,205,188},{0,ENEMY_WATCHER,286,154},{1,ENEMY_RAINLING,90,188},{1,ENEMY_RAINLING,195,150},{1,ENEMY_TICKHOUND,280,188},{2,ENEMY_SHADOW,92,188},{2,ENEMY_SHADOW,224,188},{3,ENEMY_GEARLING,70,184},{3,ENEMY_GEARLING,155,160},{3,ENEMY_GEARLING,275,184},{4,ENEMY_WATCHER,92,180},{4,ENEMY_WATCHER,230,180},{4,ENEMY_HOUR_WARDEN,160,118},{0,ENEMY_CHRONO_MITE,132,184},{2,ENEMY_CHRONO_MITE,160,184},{3,ENEMY_CHRONO_MITE,236,184}};
static int abs_i(int v){return v<0?-v:v;}
int enemies_is_boss(int kind){return kind==ENEMY_HOUR_WARDEN;}
int enemies_max_hp(int kind){return kind==ENEMY_HOUR_WARDEN?5:(kind==ENEMY_WATCHER?2:1);}
static void clamp_patrol(MokoEnemy*e,int xr,int yr){if(e->x<e->home_x-xr){e->x=e->home_x-xr;e->vx=1;}if(e->x>e->home_x+xr){e->x=e->home_x+xr;e->vx=-1;}if(e->y<e->home_y-yr){e->y=e->home_y-yr;e->vy=1;}if(e->y>e->home_y+yr){e->y=e->home_y+yr;e->vy=-1;}}
void enemies_reset(MokoEnemies*s){int i;for(i=0;i<5;i++)s->room_defeats[i]=0;s->defeats=0;for(i=0;i<MOKO_ENEMY_COUNT;i++){MokoEnemy*e=&s->e[i];e->room=spawns[i].room;e->kind=spawns[i].kind;e->x=e->home_x=spawns[i].x;e->y=e->home_y=spawns[i].y;e->vx=(i&1)?1:-1;e->vy=(i&2)?1:-1;e->hp=(uint8_t)enemies_max_hp(e->kind);e->active=e->kind==ENEMY_HOUR_WARDEN?0:1;e->phase=(uint8_t)(i*19);e->hit_cooldown=0;}}
void enemies_tick(MokoEnemies*s,int room,int px,int py){int i;if(room==4&&!s->e[12].active&&s->e[12].hp>0&&s->room_defeats[4]>=2){s->e[12].active=1;s->e[12].phase=0;s->e[12].hit_cooldown=45;}for(i=0;i<MOKO_ENEMY_COUNT;i++){MokoEnemy*e=&s->e[i];if(e->hit_cooldown){e->hit_cooldown--;if(e->active&&e->room==room){if((e->hit_cooldown&3)==0)e->x+=e->vx;clamp_patrol(e,e->kind==ENEMY_HOUR_WARDEN?70:52,e->kind==ENEMY_HOUR_WARDEN?42:30);}continue;}if(!e->active||e->room!=room)continue;e->phase++;switch(e->kind){case ENEMY_TICKHOUND:if(abs_i(px-e->x)<92&&abs_i(py-e->y)<42)e->vx=(px<e->x)?-2:2;else if(e->vx>1||e->vx<-1)e->vx=e->vx<0?-1:1;e->x+=e->vx;clamp_patrol(e,48,0);break;case ENEMY_RAINLING:e->y-=1;if(e->y<e->home_y-42)e->y=e->home_y+28;if((e->phase&15)==0)e->x+=(px<e->x)?-2:2;clamp_patrol(e,26,50);break;case ENEMY_SHADOW:if(abs_i(px-e->x)<64&&abs_i(py-e->y)<48){if((e->phase&3)==0){e->x+=(px<e->x)?-2:2;e->y+=(py<e->y)?-1:1;}}else{e->x+=e->vx;if((e->phase&31)==0)e->vx=-e->vx;}clamp_patrol(e,42,28);break;case ENEMY_GEARLING:e->x+=e->vx;if((e->phase&7)==0)e->y+=e->vy;if((e->phase&31)==0)e->vy=-e->vy;clamp_patrol(e,38,18);break;case ENEMY_WATCHER:if(abs_i(px-e->x)<110){if((e->phase&1)==0)e->x+=(px<e->x)?-1:1;if(abs_i(py-e->y)>8&&(e->phase&3)==0)e->y+=(py<e->y)?-1:1;}clamp_patrol(e,30,24);break;case ENEMY_HOUR_WARDEN:if(e->hp>=4){if(abs_i(px-e->x)<150){if((e->phase&7)<4)e->x+=(px<e->x)?-2:2;else if((e->phase&3)==0)e->y+=(py<e->y)?-2:2;}}else if(e->hp>=2){if((e->phase&15)<8){e->x+=(px<e->x)?-3:3;if((e->phase&1)==0)e->y+=(py<e->y)?-2:2;}else{e->x-=e->vx*2;if((e->phase&3)==0)e->y+=e->vy*2;}if((e->phase&15)==0){e->vx=-e->vx;e->vy=-e->vy;}}else{if((e->phase&7)<5){e->x+=(px<e->x)?-4:4;e->y+=(py<e->y)?-2:2;}else{e->x+=(px<e->x)?2:-2;}if((e->phase&7)==0){e->vx=-e->vx;e->vy=-e->vy;}}clamp_patrol(e,78,48);break;case ENEMY_CHRONO_MITE:if(abs_i(px-e->x)<74&&abs_i(py-e->y)<30){if((e->phase&7)<5)e->x+=(px<e->x)?-3:3;else e->x+=(px<e->x)?2:-2;}else{e->x+=e->vx*2;if((e->phase&15)==0)e->vx=-e->vx;}if((e->phase&7)==0)e->y=e->home_y-4;else if((e->phase&7)==3)e->y=e->home_y;clamp_patrol(e,46,6);break;}}
}
int enemies_touch(const MokoEnemies*s,int room,int px,int py,int radius){int i;for(i=0;i<MOKO_ENEMY_COUNT;i++){const MokoEnemy*e=&s->e[i];int r;if(!e->active||e->room!=room||e->hit_cooldown)continue;r=radius+(e->kind==ENEMY_HOUR_WARDEN?8:0);if(abs_i(px-e->x)<=r&&abs_i(py-e->y)<=r)return i;}return -1;}
int enemies_dash_hit(MokoEnemies*s,int room,int px,int py,int facing){int i,dx;for(i=0;i<MOKO_ENEMY_COUNT;i++){MokoEnemy*e=&s->e[i];int range;if(!e->active||e->room!=room||e->hit_cooldown||abs_i(py-e->y)>(e->kind==ENEMY_HOUR_WARDEN?30:22))continue;dx=e->x-px;range=e->kind==ENEMY_HOUR_WARDEN?46:38;if((facing>=0&&dx>=0&&dx<range)||(facing<0&&dx<=0&&dx>-range)){if(e->hp)e->hp--;e->x+=facing>=0?10:-10;e->vx=facing>=0?2:-2;if(e->hp)e->hit_cooldown=e->kind==ENEMY_HOUR_WARDEN?(e->hp==1?18:30):(e->kind==ENEMY_WATCHER?22:14);else{e->active=0;s->defeats++;if(room>=0&&room<5)s->room_defeats[room]++;}return i;}}return -1;}
int enemies_room_remaining(const MokoEnemies*s,int room){int i,n=0;for(i=0;i<MOKO_ENEMY_COUNT;i++)if(s->e[i].room==room&&s->e[i].hp>0)n++;return n;}
int enemies_room_cleared(const MokoEnemies*s,int room){int i,spawned=0;if(room<0||room>=5)return 0;for(i=0;i<MOKO_ENEMY_COUNT;i++)if(s->e[i].room==room)spawned++;return spawned>0&&s->room_defeats[room]>=spawned;}
int enemies_defeats(const MokoEnemies*s){return s?s->defeats:0;}
const MokoEnemy*enemies_get(const MokoEnemies*s,int index){return(index>=0&&index<MOKO_ENEMY_COUNT)?&s->e[index]:0;}
