#include "enemies.h"
typedef struct {uint8_t room,kind;short x,y;} Spawn;
static const Spawn spawns[MOKO_ENEMY_COUNT]={{0,ENEMY_TICKHOUND,205,188},{0,ENEMY_WATCHER,286,154},{1,ENEMY_RAINLING,90,188},{1,ENEMY_RAINLING,195,150},{1,ENEMY_TICKHOUND,280,188},{2,ENEMY_SHADOW,92,188},{2,ENEMY_SHADOW,224,188},{3,ENEMY_GEARLING,70,184},{3,ENEMY_GEARLING,155,160},{3,ENEMY_GEARLING,275,184},{4,ENEMY_WATCHER,92,180},{4,ENEMY_WATCHER,230,180}};
static int abs_i(int v){return v<0?-v:v;}
void enemies_reset(MokoEnemies*s){int i;for(i=0;i<MOKO_ENEMY_COUNT;i++){s->e[i].room=spawns[i].room;s->e[i].kind=spawns[i].kind;s->e[i].x=spawns[i].x;s->e[i].home_x=spawns[i].x;s->e[i].y=spawns[i].y;s->e[i].vx=(i&1)?1:-1;s->e[i].hp=(spawns[i].kind==ENEMY_WATCHER)?2:1;s->e[i].active=1;s->e[i].phase=(uint8_t)(i*19);s->e[i].hit_cooldown=0;}}
void enemies_tick(MokoEnemies*s,int room,int px,int py){int i;for(i=0;i<MOKO_ENEMY_COUNT;i++){MokoEnemy*e=&s->e[i];if(e->hit_cooldown)e->hit_cooldown--;if(!e->active||e->room!=room)continue;e->phase++;if(abs_i(px-e->x)<72&&abs_i(py-e->y)<38)e->vx=(px<e->x)?-1:1;e->x+=e->vx;if(e->x<e->home_x-36){e->x=e->home_x-36;e->vx=1;}if(e->x>e->home_x+36){e->x=e->home_x+36;e->vx=-1;}}}
int enemies_touch(const MokoEnemies*s,int room,int px,int py,int radius){int i;for(i=0;i<MOKO_ENEMY_COUNT;i++){const MokoEnemy*e=&s->e[i];if(e->active&&e->room==room&&abs_i(px-e->x)<=radius&&abs_i(py-e->y)<=radius)return i;}return -1;}
int enemies_dash_hit(MokoEnemies*s,int room,int px,int py,int facing){int i,dx;for(i=0;i<MOKO_ENEMY_COUNT;i++){MokoEnemy*e=&s->e[i];if(!e->active||e->room!=room||e->hit_cooldown||abs_i(py-e->y)>22)continue;dx=e->x-px;if((facing>=0&&dx>=0&&dx<38)||(facing<0&&dx<=0&&dx>-38)){if(e->hp)e->hp--;if(e->hp)e->hit_cooldown=16;else e->active=0;return i;}}return -1;}
const MokoEnemy*enemies_get(const MokoEnemies*s,int index){return(index>=0&&index<MOKO_ENEMY_COUNT)?&s->e[index]:0;}
