#include "quests.h"
typedef struct {const char*name;const char*hint;uint16_t reward;uint8_t target;uint8_t kind;} QuestDef;
static const QuestDef defs[MOKO_QUEST_COUNT]={
{"Wake Between Minutes","Reach the Silent Station clock.",100,1,QUEST_MAIN},{"Station Signal","Restore the dead platform signal.",150,1,QUEST_MAIN},{"Echo in the Glass","Find the Station Memory Echo.",125,1,QUEST_SIDE},{"No Time to Wait","Clear Station without taking damage.",200,1,QUEST_SIDE},{"Two Red Switches","Activate both street switches.",175,2,QUEST_MAIN},{"Against the Current","Cross both backward pulses.",150,2,QUEST_SIDE},{"Lost Umbrella","Search the far end of Backward Street.",125,1,QUEST_SIDE},{"Street Echo","Find the memory hiding in the rain.",125,1,QUEST_SIDE},{"House Without Dawn","Open the sealed morning room.",200,1,QUEST_MAIN},{"Three Cold Windows","Inspect three frozen windows.",150,3,QUEST_SIDE},{"Breakfast Never Came","Find what was left on the table.",175,1,QUEST_SIDE},{"House Echo","Recover the family's Memory Echo.",125,1,QUEST_SIDE},{"Wake the Clockworks","Restart the central gear.",225,1,QUEST_MAIN},{"Dash the Red Gates","Pass two temporal gates while dashing.",200,2,QUEST_SIDE},{"Gear Collector","Recover three loose time cogs.",225,3,QUEST_SIDE},{"Clockworks Echo","Find the machinist's Memory Echo.",125,1,QUEST_SIDE},{"Four Missing Hours","Recover all four Memory Shards.",500,4,QUEST_MAIN},{"Memory Keeper","Recover every Memory Echo.",400,4,QUEST_SIDE},{"Chain of Eight","Reach an eight-action memory combo.",300,8,QUEST_SIDE},{"Perfect Focus","Reach a chamber with full Focus.",200,1,QUEST_SIDE},{"Restore the Sockets","Return four shards to the clock.",400,4,QUEST_MAIN},{"Hold the Lost Hour","Stabilize the fractured clock.",600,1,QUEST_MAIN},{"Nothing Forgotten","Clear the first event collection.",750,22,QUEST_SECRET},{"The Hidden Minute","Discover the hidden minute.",1000,1,QUEST_SECRET},
{"Ticket for Nobody","Find the ticket stamped 00:00.",150,1,QUEST_SIDE},{"Platform Thirteen","Discover the platform that is not on the map.",250,1,QUEST_SECRET},{"Last Train Home","Hear the phantom train pass three times.",175,3,QUEST_SIDE},{"Station Cat","Follow the clockwork cat to its hiding place.",175,1,QUEST_SIDE},{"Rain Goes Up","Stand beneath three reverse rain streams.",150,3,QUEST_SIDE},{"Letter Never Sent","Recover a soaked letter from Backward Street.",200,1,QUEST_SIDE},{"Red Door Blue Key","Find the blue key and open the red door.",250,2,QUEST_SIDE},{"The Walking Lamp","Catch the street lamp that changes position.",225,1,QUEST_SECRET},{"Family Portrait","Restore four missing pieces of a photograph.",250,4,QUEST_SIDE},{"Tea at Midnight","Bring the cold teacup to the frozen table.",175,2,QUEST_SIDE},{"Under the Bed","Find what keeps scratching beneath the floor.",225,1,QUEST_SECRET},{"Morning Bird","Wake the mechanical bird before dawn.",175,1,QUEST_SIDE},{"Seven Tiny Gears","Collect seven escaped clockwork gears.",300,7,QUEST_SIDE},{"Wrong Way Conveyor","Cross the reverse belt without being hit.",225,1,QUEST_SIDE},{"Mechanic's Lunch","Return the forgotten lunchbox.",150,1,QUEST_SIDE},{"Bell Without a Rope","Make the hidden factory bell ring.",250,1,QUEST_SECRET},{"Dash Apprentice","Perform five successful Memory Dashes.",200,5,QUEST_SIDE},{"Dash Master","Perform twenty successful Memory Dashes.",450,20,QUEST_SIDE},{"Untouchable Minute","Finish an area at full health.",250,1,QUEST_SIDE},{"Memory Chain","Reach a combo of six.",200,6,QUEST_SIDE},{"Clock Whisperer","Hear all three whispers inside the chamber.",350,3,QUEST_SIDE},{"Forty Events","Complete forty Lost Hour events.",500,40,QUEST_SECRET},{"Nothing Left Behind","Complete every non-meta event.",900,50,QUEST_SECRET},{"The Sixtieth Second","Complete every quest and every delivery.",1500,1,QUEST_SECRET},
{"Platform Sweep","Defeat both time-creatures in Silent Station.",225,2,QUEST_SIDE},{"Rain Breaker","Defeat all three time-creatures in Backward Street.",250,3,QUEST_SIDE},{"Shadow House","Drive both shadows from the House Without Morning.",275,2,QUEST_SIDE},{"Gear Grinder","Defeat all three clockwork creatures in the Clockworks.",300,3,QUEST_SIDE},{"Last Watch","Defeat both Watchers in the Clock Chamber.",400,2,QUEST_SIDE}};
static int clear_count(const MokoQuests*q,int first,int last){int i,n=0;for(i=first;i<=last;i++)if(quests_is_clear(q,i))n++;return n;}
static int non_meta_clear(const MokoQuests*q){return clear_count(q,0,44)+clear_count(q,48,52);}
static void set_progress_max(MokoQuests*q,int id,int value){if(id<0||id>=MOKO_QUEST_COUNT||q->state[id]==QUEST_CLEAR)return;if(value>q->progress[id])q->progress[id]=(uint8_t)value;if(q->progress[id]>=q->target[id])quests_clear(q,id);}
void quests_reset(MokoQuests*q){int i;q->ap=0;q->cleared=0;q->secrets=0;for(i=0;i<MOKO_QUEST_COUNT;i++){q->state[i]=QUEST_LOCKED;q->progress[i]=0;q->target[i]=defs[i].target;}for(i=0;i<4;i++)q->state[i]=QUEST_ACTIVE;}
int quests_trigger(MokoQuests*q,int id){if(id<0||id>=MOKO_QUEST_COUNT||q->state[id]!=QUEST_LOCKED)return 0;q->state[id]=QUEST_ACTIVE;return 1;}
int quests_clear(MokoQuests*q,int id){if(id<0||id>=MOKO_QUEST_COUNT||q->state[id]==QUEST_CLEAR)return 0;q->state[id]=QUEST_CLEAR;q->progress[id]=q->target[id];q->ap+=defs[id].reward;q->cleared++;if(defs[id].kind==QUEST_SECRET)q->secrets++;return defs[id].reward;}
int quests_add(MokoQuests*q,int id,int amount){if(id<0||id>=MOKO_QUEST_COUNT||q->state[id]==QUEST_LOCKED||q->state[id]==QUEST_CLEAR)return 0;if(amount<1)amount=1;if(q->progress[id]+amount>=q->target[id])return quests_clear(q,id);q->progress[id]+=amount;return 0;}
int quests_is_clear(const MokoQuests*q,int id){return id>=0&&id<MOKO_QUEST_COUNT&&q->state[id]==QUEST_CLEAR;}int quests_completion(const MokoQuests*q){return(q->cleared*100)/MOKO_QUEST_COUNT;}int quests_all_clear(const MokoQuests*q){return q->cleared>=MOKO_QUEST_COUNT;}const char*quests_name(int id){return(id>=0&&id<MOKO_QUEST_COUNT)?defs[id].name:"Unknown Event";}const char*quests_hint(int id){return(id>=0&&id<MOKO_QUEST_COUNT)?defs[id].hint:"";}int quests_reward(int id){return(id>=0&&id<MOKO_QUEST_COUNT)?defs[id].reward:0;}int quests_kind(int id){return(id>=0&&id<MOKO_QUEST_COUNT)?defs[id].kind:QUEST_SIDE;}
void quests_tick(MokoQuests*q,int room,int shards,int echoes,int combo,int health,int focus){int i,n;if(room>=1){quests_clear(q,0);for(i=4;i<=7;i++)quests_trigger(q,i);for(i=24;i<=31;i++)quests_trigger(q,i);}if(room>=2){for(i=8;i<=11;i++)quests_trigger(q,i);for(i=32;i<=35;i++)quests_trigger(q,i);}if(room>=3){for(i=12;i<=15;i++)quests_trigger(q,i);for(i=36;i<=39;i++)quests_trigger(q,i);}if(room>=4){for(i=19;i<=21;i++)quests_trigger(q,i);for(i=40;i<=44;i++)quests_trigger(q,i);if(focus>=100)quests_clear(q,19);}for(i=48;i<=48+room&&i<=52;i++)quests_trigger(q,i);quests_trigger(q,16);set_progress_max(q,16,shards);quests_trigger(q,17);set_progress_max(q,17,echoes);quests_trigger(q,18);set_progress_max(q,18,combo);quests_trigger(q,43);set_progress_max(q,43,combo);n=clear_count(q,0,21);q->progress[22]=(uint8_t)n;if(n>=22){quests_trigger(q,22);quests_clear(q,22);}n=non_meta_clear(q);q->progress[45]=(uint8_t)n;if(n>=40){quests_trigger(q,45);quests_clear(q,45);}q->progress[46]=(uint8_t)n;if(n>=50){quests_trigger(q,46);quests_clear(q,46);}}
